# 章节9(课时79~课时84)    
## 异常概念   
> **什么是异常？**   
> &ensp;&ensp;&ensp;&ensp;所谓异常是指在程序运行的过程中发生的一些不正常事件。（如除0溢出，数组下标越界，所要读取的文件不存在）。    
> **导致的后果？**    
> &ensp;&ensp;&ensp;&ensp;Java程序的执行过程中如出现异常事件，可以生成一个异常类对象，该异常对象封装了异常事件的信息，并将其被提交给java运行时系统，这个过程称为抛出异常，不处理的话会直接导致程序直接中断。   
> **如何防止程序中断**    
> &ensp;&ensp;&ensp;&ensp;设计良好的程序应该在程序异常发生时提供处理这些异常的方法，使得程序不会因为异常的发生而阻断或产生不可预见的结果。   
## 异常分类   
<img src="http://img.my.csdn.net/uploads/201211/27/1354020417_5176.jpg">  

|异常类型|包括|来源|处理|
|:-:|:-:|:-:|:-:|
|受查异常<br/>checkedException|Exception及其子类(不包括<br/>RuntimeException及其子类)|由代码控制能力之<br/>外的因素导致的运<br/>行时错误|必须要理解，否则<br/>通不过编译|
|非受查异常<br/>uncheckedException|Error和RuntimeException<br/>及其子类|RuntimeException<br/>一般代表编程错误|可以不用处理|
## Java异常处理机制    
> **Java的异常是通过两种机制来处理的**    
> &ensp;&ensp;&ensp;&ensp;**捕获：**`try-catch-finally`    
> &ensp;&ensp;&ensp;&ensp;**抛出：**`throw,throws`     
## try-catch-finally    
> **try{}语句块中放的是要检测的java代码，可能有会抛出异常，也可能会正常执行。**    
> **catch(异常类型){}块是当Java运行时系统接收到try块中所抛出异常对象时，会寻找能处理这一异常catch块来进行处理（可以有多个catch块）。**    
> **finally{}不管系统有没有抛出异常都会去执行，一般用来释放资源。除了在之前执行了System.exit(0)**    
```
import java.util.Scanner;
import java.util.InputMismatchException;
public class ExceptionDemo1{
    public static void main(String []args){
        testTryFinally(null);
        /*System.out.println("请输入一个数字");
        Scanner input=new Scanner(System.in);
        int res=0;
        try{
            //return;
            System.exit(0);
            /*int number=input.nextInt();
            res=10/number;*/
        }catch(InputMismatchException e){
            System.out.println(e.getMessage());
            e.printStackTrace();
        }catch(ArithmeticException e){
            System.out.println(e.getMessage());
            e.printStackTrace();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }finally{
            //释放资源，比如关闭打开的文件，删除一些临时文件等
            System.out.println("结果为："+res);
        }*/
    }
    
    public static void testTryFinally(String name){
        try{
            System.out.println(name.length());
        }finally{
            System.out.println("end");
        }
    }
}
```
## throw和throws   
> - **throw用于手动抛出异常。作为程序员可以在任意位置手动抛出异常**    
> - **throws用于在方法上标识要暴露的异常。抛出的异常交由调用者处理。**    
> - **两者区别**    
> &ensp;&ensp;&ensp;&ensp;throw用在方法内，后面跟上要抛出的异常类对象   
> &ensp;&ensp;&ensp;&ensp;throws修饰在方法上，告诉调用者此方法可能会抛出异常，后面跟上可能要抛出的异常类名   
```
public class ExceptionDemo2{
    public static void main(String []args){
        Bar bar=new Bar();
        try{
            bar.enter(15);
        }catch(Exception e){
            System.out.println("错误信息："+e.getMessage());
        }
        System.out.println("end");
    }
}

class Bar{
    public void enter(int age)throws Exception{
        if(age<18){
            //受查异常(必须捕获，不捕获编译都通不过)和非受查异常
            //throw new IllegalArgumentException("年龄不合格");
            throw new Exception("年龄不合格");
        }else{
            System.out.println("欢迎光临");
        }
    }
}
```
## 自定义异常  
> - **常见异常**    
> &ensp;&ensp;&ensp;&ensp;RuntimeException,IOException,SQLException,ClassNotFoundException    
> - **自定义异常异常**    
> &ensp;&ensp;&ensp;&ensp;Java提供的异常体系不可能预见所有希望加以报告的错误   
> - **自定义异常类必须从已有的异常类继承**    
> - **建立新的异常类型最简单的方法就是让编译器产生默认构造方法**    
> - **对来说，最重要的部分就是它的类名**    
> - **可以为异常类定义一个接受字符串参数的构造方法，字符串参数描述异常信息**    
```
public class ExceptionDemo3{
    public static void main(String []args){
        Bar bar=new Bar();
        try{
            bar.enter(15);
        }catch(AgeLessThanEighteenException e){
            System.out.println("错误信息："+e.getMessage());
        }
        System.out.println("end");
    }
}

//自定义了一个异常类
class AgeLessThanEighteenException extends Exception{
    private String message;//描述异常信息
    public AgeLessThanEighteenException(String message){
        this.message=message;
    }
    public String getMessage(){
        return message;
    }
}

class Bar{
    public void enter(int age)throws AgeLessThanEighteenException{
        if(age<18){
            throw new AgeLessThanEighteenException("年龄不合格");
        }else{
            System.out.println("欢迎光临");
        }
    }
}
```
## 案例讲解--医生给工作者看病   
```
import java.util.Random;
public class ExceptionTest{
    public static void main(String []args){
        Worker worker=new Worker();
        Doctor doctor=new Doctor();
        try{
            worker.work();
        }catch(SickException e){
            doctor.cure(worker);
            if(worker.getStatus().equals("健康")){
                System.out.println("恭喜你可以恢复了");
            }else{
                System.out.println("sorry,尽力了");
            }
        }finally{
            System.out.println("欢迎下次再来");
        }
    }
}

class Worker{
    private String status;
    public void setStatus(String status){
        this.status=status;
    }
    public String getStatus(){
        return status;
    }
    
    public void work()throws SickException{
        Random random=new Random();
        int rad=random.nextInt(3)+1;
        if(rad==1){
            //抛出一个自定义异常对象
            throw new SickException("我有病");
        }else{
            System.out.println("身体健康，不用治疗");
        }
    }
}

class SickException extends Exception{
    private String message;
    public SickException(String message){
        this.message=message;
    }
    public String getMessage(){
        return message;
    }
}

class Doctor{
    public void cure(Worker worker){
        Random random=new Random();
        int rad=random.nextInt(2)+1;
        if(rad==1){
            worker.setStatus("健康");
        }else{
            worker.setStatus("死亡");
        }
    }
}
```
